name: Build
on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yaml'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            goamd64: v1
            suffix: amd64
          - goos: linux
            goarch: "386"
            go386: sse2
            suffix: x86
          - goos: linux
            goarch: arm64
            goarm64: v8.0
            suffix: arm64
          - goos: linux
            goarch: arm
            goarm: "7"
            suffix: arm32
          - goos: linux
            goarch: riscv64
            goriscv64: rva20u64
            suffix: riscv64
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: '1.25'

      - run: go vet ./...

      - name: Get build metadata
        id: name 
        run: |
          echo "name=packman-${{ matrix.suffix }}-$(git show -s --format=%cd --date=format:'%Y%m%d' HEAD)-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
          GOAMD64: ${{ matrix.goamd64 }}
          GO386: ${{ matrix.go386 }}
          GOARM64: ${{ matrix.goarm64 }}
          GORISCV64: ${{ matrix.goriscv64 }}
        run: CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o ${{ steps.name.outputs.name }} ./...

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.name.outputs.name }}
          path: ${{ steps.name.outputs.name }}
